apiVersion: apps/v1beta2 # for kubectl versions >= 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: my-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-redis-app
  template:
    metadata:
      labels:
        app: my-redis-app
    spec:
      containers:
      - name: my-redis
        image: redis
        ports:
        - containerPort: 6379







